name: ClipDock
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 7
    MARKETING_VERSION: 0.2.5
    CODE_SIGN_STYLE: Automatic
configs:
  Debug: debug
  Release: release
targets:
  ClipDock:
    type: application
    platform: iOS
    sources:
      - path: ClipDock
    resources:
      - path: ClipDock/Resources
    info:
      path: ClipDock/Info.plist
      properties:
        CFBundleDisplayName: ClipDock
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        NSPhotoLibraryUsageDescription: ClipDock needs access to scan and export videos from your photo library.
        NSPhotoLibraryAddUsageDescription: ClipDock needs permission to delete migrated videos from your photo library.
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wenfeng.clipdock
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
