name: Bug report
description: Report something that isn't working
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include enough detail to reproduce.

  - type: input
    id: app_version
    attributes:
      label: App version
      description: From Settings or the about screen (e.g. 0.2.6 (7))
      placeholder: "0.2.6 (7)"

  - type: input
    id: ios_version
    attributes:
      label: iOS version
      placeholder: "17.x"

  - type: input
    id: device
    attributes:
      label: Device model
      placeholder: "iPhone 15 Pro"

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you see?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Drag-and-drop screenshots, or paste log snippets.

